### ISSUE TITLE
MVP Milestones 

### ISSUE THREAD

**Issue by KeplerC** [KeplerC/fogros2-rt-x#1]
Implementation
- [x] cloud interfacing 
- [x] management with relational db
- [x] tagging support
- [x] output based on tags (mix and match existing datasets?)
- [x] orchestration of different data streams
- [x] generating ROS2 message type with cli
- [ ] automatically cloud creation (google bucket, google big query table)
- [ ] gathering episode/dataset metadata 
- [ ] separate step info with other information; use tag for step metadata 
- [x] clean up the orchestrator part

Improvements
- [x] Support multi dimensional tensor conversion to ros2
- [x] default ros2 parameters 
- [x] automatically figure out the array size

Polishing 
- [ ] Flexible dataset exporting scheme 

Other things 
- [ ] verify that input and output are the same (test cases)
- [ ] test and make it work with more datasets 
- [ ] setup readme instructions 
- [ ] cloud setup instructions (other readmes)

examples 
- [x] an example of how user publish step message 

error handling
- [ ] data types not match for the recorder (e.g. dimension checks)
